// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pccmhleiozmdqhlblmxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjY21obGVpb3ptZHFobGJsbXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODkwNTcsImV4cCI6MjA3MTA2NTA1N30.qzGqGiM1chYo_ZVOtMorH38ugPfZbybsVik1yf_oh-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});